sudo: false
language: go

go:
  - 1.5
  - 1.6
  - tip

cache:
  directories:
    - vendor

install:
  - make install_ci

script:
  - make test_ci
  - travis_retry goveralls -coverprofile=cover.out -service=travis-ci
